[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "logging>=0.4.9.6",
    "pydantic>=2.11.1",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.0",
]
