"""add instructions

Revision ID: 28c83c66dfe5
Revises: fa123273a074
Create Date: 2025-04-02 20:56:39.189181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c83c66dfe5'
down_revision: Union[str, None] = 'fa123273a074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_instruction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_instruction')
    # ### end Alembic commands ###
