"""planned food

Revision ID: fb163eab6b9c
Revises: f6b20e0ed94c
Create Date: 2025-04-03 13:23:34.592120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb163eab6b9c'
down_revision: Union[str, None] = 'f6b20e0ed94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_food', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('planned_food', sa.Column('servings', sa.Float(), nullable=False))
    op.add_column('planned_food', sa.Column('eaten', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_food', 'eaten')
    op.drop_column('planned_food', 'servings')
    op.drop_column('planned_food', 'date')
    # ### end Alembic commands ###
