"""cascade source recipe

Revision ID: f6b20e0ed94c
Revises: 7565ae3336a7
Create Date: 2025-04-03 00:05:49.581179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b20e0ed94c"
down_revision: Union[str, None] = "7565ae3336a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        # Replace 'None' with the actual constraint name
        batch_op.create_foreign_key('fk_food_source_recipe_id_recipe', 'recipe', ['source_recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_constraint('fk_food_source_recipe_id_recipe', type_='foreignkey')
        batch_op.create_foreign_key('fk_food_source_recipe_id_recipe', 'recipe', ['source_recipe_id'], ['id'])
    # ### end Alembic commands ###
