"""cascade recipe relations

Revision ID: 7565ae3336a7
Revises: 85f206e55748
Create Date: 2025-04-02 21:25:43.639951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7565ae3336a7"
down_revision: Union[str, None] = "85f206e55748"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        # We need to find the actual name of the constraint instead of using None
        # batch_op.drop_constraint("fk_recipe_ingredient_recipe_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_recipe_ingredient_recipe_id",
            "recipe",
            ["recipe_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("recipe_instruction", schema=None) as batch_op:
        # batch_op.drop_constraint("fk_recipe_instruction_recipe_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_recipe_instruction_recipe_id",
            "recipe",
            ["recipe_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instruction", schema=None) as batch_op:
        batch_op.drop_constraint("fk_recipe_instruction_recipe_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_recipe_instruction_recipe_id",
            "recipe",
            ["recipe_id"],
            ["id"],
        )

    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.drop_constraint("fk_recipe_ingredient_recipe_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_recipe_ingredient_recipe_id", "recipe", ["recipe_id"], ["id"]
        )
    # ### end Alembic commands ###
