"""empty message

Revision ID: fa123273a074
Revises: ba51ec1d77ce
Create Date: 2025-04-02 20:07:30.719542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa123273a074'
down_revision: Union[str, None] = 'ba51ec1d77ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PLANNED', 'UNCOOKED', 'READY', name='foodstate'), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id', 'state')
    )
    op.create_table('planned_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('recipe_ingredient', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredient', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_table('planned_food')
    op.drop_table('inventory')
    # ### end Alembic commands ###
