"""Initial migration

Revision ID: 9a637e1f9c3e
Revises: 
Create Date: 2025-04-02 19:34:08.575170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a637e1f9c3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('source_recipe_id', sa.Integer(), nullable=True),
        sa.Column('serving_size', sa.Float(), nullable=False),
        sa.Column('serving_size_unit', sa.String(), nullable=False),
        sa.Column('calories', sa.Integer(), nullable=False),
        sa.Column('fat', sa.Integer(), nullable=False),
        sa.Column('protein', sa.Integer(), nullable=False),
        sa.Column('carbohydrates', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['source_recipe_id'], ['recipe.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('override_nutrition', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredient',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('food_id', sa.Integer(), nullable=False),
        sa.Column('note', sa.String(), nullable=False),
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
        sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient')
    op.drop_table('recipe')
    op.drop_table('food')
    # ### end Alembic commands ###
